apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-product-go-micro.fullname" . }}
  labels:
    {{- include "helm-product-go-micro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "helm-product-go-micro.selectorLabels" . | nindent 4 }}
